# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/ghen-git/Thirst-Mod/issues"
[[mods]]
modId="thirst"
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
version="1.3.5"
displayName="Do Or Die: Thirst"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/ghen-git/Thirst-Mod"
credits="Thirst was taken for inspiration and parts of code"
authors="IndEvo Studio"
description='''
A lightweight mod adding thrist system to minecraft.
'''
[[dependencies.thirst]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thirst]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"
